name: AreaPlanter
version: '1.2'
main: io.github.mrgucci1.areaPlanter.AreaPlanter
api-version: '1.21'
load: STARTUP
authors: [mrgucci1]
description: Plants configurable areas of crops.
permissions:
  areaplanter.admin:
    default: op